title: Prepare to run a Code Club - Week 2
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: 1
  - title: 2
  - title: 3
  - title: 4
  - title: 5
  - title: 6
  - title: 7
  - title: 8
  - title: 9
  - title: 10
  - title: 11
  - title: 12
  - title: 13
  - title: 14